### ISSUE TITLE
Tradition Character Stroke Data

### ISSUE THREAD

**Issue by TomClarkson** [chanind/hanzi-writer#12]
I am building a Kanji learning app and I would like to be able to provide stroke data for traditional characters.

Do you know of anywhere online/or a method I could use to could obtain the stroke data for traditional characters in ZDT format?

**Comment by fzzylogic** [comment]
Hi, replying here as there's a tiny chance it may be useful to the hanzi-writer project..

I don't know of publicly available ZDT like data other than ZDT itself and this project (and i suspect the ZDT data is similar to other non-public data, for example data used in some university courses hinted at by this fine effort: https://github.com/chaseconley/hanzi). 
However, you might be interested in https://github.com/skishore/makemeahanzi. This apparently includes traditional and simplified data (stroke data is in graphics.txt). It is in SVG format (https://www.w3.org/TR/SVG/paths.html), not ZDT format, but depending on your needs, converting it may be acceptable.

Converting it to ZDT format presents some problems. For one, a single stroke is a single path, unlike ZDT which breaks strokes up into multiple paths depending on the direction. Also, it does not indicate which paths are part of a radical. Character information is in a separate file called dictionary.txt.  All the same, it's possible to convert it into something very much like ZDT data quite easily (except 1. without the stroke info prefix, 2. with fewer paths bcs each path equals an entire stroke and 3. upside down... : ).

About the paths, the main coordinate difference is that the paths in the ZDT data are drawn using points, whereas makemeahanzi paths use bezier curves. With bezier curves there are two coordinates instead of one. So just drop the first coordinate pair from each of the Q coords in the svg string to get a non-smooth version of the path (this often doesn't look as bad as it sounds). 

Makemeahanzi also provides animated SVG's of all characters, if that will work for you.

**Comment by chanind** [comment]
Wow that's awesome, thanks for sharing @fzzylogic! I didn't know about makemeahanzi. I've been trying to find a better datasource to power hanziwriter since ZDT's character data is honestly just not very consistent. I made the [Wenlin CDL Javascript library](http://wenlincdl.com) with Wenlin's data but it would be great to find a free and open source dataset for HanziWriter. It looks like makemeahanzi might just be exactly that!

**Comment by fzzylogic** [comment]
Thanks for sharing Wenlin CDL javascript library link, that is useful to know about, since the data-set is so comprehensive and I didn't know it was possible to get access to it in that way.

**Comment by chanind** [comment]
I updated Hanzi Writer to use https://github.com/skishore/makemeahanzi as its data source instead of ZDT. Make Me a Hanzi seems to be a lot higher quality than the ZDT data it was using before. Thanks again for flagging @fzzylogic!

**Comment by fzzylogic** [comment]
Wow, that's really good news. Thank you for your work on this!
