### ISSUE TITLE
Feature request: kanji support

### ISSUE THREAD

**Issue by TowelSniffer** [chanind/hanzi-writer#132]
Is it possible that this will ever include Japanese characters?

**Comment by chanind** [comment]
It should be doable - there's a Japanese dataset using the same format in https://raw.githubusercontent.com/parsimonhi/animCJK/master/graphicsJa.txt, just need to process it and get it into a CDN

**Comment by chanind** [comment]
I put a repo up with Japanese data from [animCJK](https://github.com/parsimonhi/animCJK) here: https://github.com/chanind/hanzi-writer-data-jp. You can use this in Hanzi Writer via a custom `charDataLoader` function, like below:

```
HanziWriter.create('target-div', '私', {
  width: 400,
  height: 400,
  charDataLoader: (char, onLoad, onError) => {
    fetch(`https://cdn.jsdelivr.net/npm/hanzi-writer-data-jp@0/${char}.json`)
      .then(res => res.json())
      .then(onLoad)
      .catch(onError);
  }
})
```

This Japanese data is limited compared to the Chinese currently due to:
- The data does not support radicals yet
- The data does not have capped strokes, so there are sharp edges where strokes intersect

I'll work on tidying this up before making an official release in HanziWriter adding first-class support for this data. I also want to double-check with animCJK that using the data this way is alright.

This is also discussed in https://github.com/chanind/hanzi-writer-data/issues/2

**Comment by TowelSniffer** [comment]
You are amazing man :)

**Comment by ganqqwerty** [comment]
is there any update on this? I'd like to use it for the Anki cards for Japanese
