### ISSUE TITLE
How can I repeat the animation forever?

### ISSUE THREAD

**Issue by webmagnets** [chanind/hanzi-writer#17]
Sorry for this noob question, but how can I get the animation to repeat over and over again?

**Comment by chanind** [comment]
Were you able to figure this out? Apologies for the lack of clear documentation about this - I'll work on improving the docs soon since this is probably a really common use-case. The easiest way to accomplish this currently is to use the `onComplete` callback to initiate another animation. As an example:

```js
var char = new HanziWriter('target-div', '我', {/* extra opts */});
var loopAnimation = function() {
  // call the loop function again when complete
  char.animateCharacter({onComplete: loopAnimation});
};
loopAnimation();
```
