### ISSUE TITLE
Hangul characters

### ISSUE THREAD

**Issue by p3drogit** [chanind/hanzi-writer#173]
First of all congratulations @chanind for this great project 🥇 I made a really simple website based on it [https://hanzi.pedrocorreia.net/](https://hanzi.pedrocorreia.net/)

I know that this is not the best place to make this question, and please feel free to close or delete this post, do you know where I can get something similar, but with Hangul characters?

Thank you and keep up the good work!

**Comment by chanind** [comment]
Your website looks great!! Really like the numbers at the start of the strokes.

I don't have any info about Hangul unfortunately. It would be hard to do with Hanzi Writer without some changes to how it does rendering since Hangul has strokes that loop back on themselves, which will break with how Hanzi writer renders SVG. It's possible to overcome I think, but would require doing something like breaking up each stroke into segments that animate in sequence so the overlapping parts don't look weird.

**Comment by p3drogit** [comment]
I'm really glad you liked the website @chanind , you made my day :)

Thank you for the detailed explanation, I'll try to search a little bit more.

Best regards!

**Comment by chanind** [comment]
Good luck! I'll close this issue for now, but feel free to re-open if you have more info or a new approach to try!
