### ISSUE TITLE
loadCharacterData() the method can't be used in wechat miniprograms

### ISSUE THREAD

**Issue by hkai1221** [chanind/hanzi-writer#180]
![image](https://user-images.githubusercontent.com/48352768/88152053-0dcc1400-cc36-11ea-950b-0ec9aace4012.png)
 // You can call any normal HanziWriter method here
but
![image](https://user-images.githubusercontent.com/48352768/88151003-b37e8380-cc34-11ea-8274-daba628c719f.png)
There is no loadCharacterData method.

**Comment by chanind** [comment]
`loadCharacterData` isn't an instance method - it's just a static method on the `HanziWriter` class for convenience. In miniprograms this probably won't work though because miniprograms use their own APIs for doing network requests. You can see the character loading logic in https://github.com/chanind/hanzi-writer-miniprogram/blob/master/src/defaultCharDataLoader.js and just copy this logic if you need in your miniprogram

**Comment by hkai1221** [comment]
Very helpful, thanks 😃
