### ISSUE TITLE
Can I add a single tap (onclick action) on hanzi-writer target in quiz mode?

### ISSUE THREAD

**Issue by kieuquangloc** [chanind/hanzi-writer#204]
Hi @chanind , can I add a single tap **addEventListener** (onclick action) on hanzi-writer on quiz mode?

```
let divTarget = document.getElementById('target')
  if(divTarget){
    divTarget.addEventListener('click', sendMessageTapOnTarget)
  }
```
it is working if I just show the character, but it is stoped working if I use with **quiz** mode
```
let options = {
    onMistake: onQuizMistake,
    onCorrectStroke: onQuizCorrectStroke,
    onComplete: onQuizComplete,
  }
  writer.quiz(options);
```

**Comment by chanind** [comment]
that's tricky, since Hanzi Writer intercepts the touch / mouse events in quiz mode to detect that the user is drawing. Maybe we can add an option to not prevent default to allow click to still work? The problem is then the screen will start scrolling and highlighting and stuff as the user draws strokes since the browser will interpret the clicks and drags as just normal events 🤔

**Comment by kieuquangloc** [comment]
@chanind thank you for the answer, I will find another method to override the tap action before it is passed to the div of Hanzi Writer
