### ISSUE TITLE
Consider writing more detailed documentation on getting this set up

### ISSUE THREAD

**Issue by NinKenDo64** [chanind/hanzi-writer#25]
Awesome tool, but I can't for the life of me get a basic page set up to work with it. While I'm by no means an expert, I have basic webdev knowledge and skillset that should be sufficient to get something like this working. Yet even after reading through the source for the demo pages I haven't made one iota of progress. I'm sure there's just some minor step I'm missing. A simple step-by-step on how get get a single page with a canvas and a character animation and/or quiz would be a huge help.

**Comment by chanind** [comment]
You're right that documentation is a weak link right now. I'm working on redoing the website and improving documentation now, hopefully it will be ready to go in the next week. In the meantime, where are you struggling with the setup? Is there an error you're getting? Are you using install from NPM or are you loading the javascript directly in a webpage?

**Comment by chanind** [comment]
I pushed a new version of the site with improved docs here: http://chanind.github.io/hanzi-writer/docs.html. I'm going to continue working on these docs so they're more complete. Do these docs make it clearer? If there's anything that's still not working or that you have questions about please continue to post here. It's helpful to know what the stumbling blocks are so that we can improve the docs and the library.

**Comment by chanind** [comment]
Closing this issue for now. Feel free to create another issue for any individual questions you may have!
