### ISSUE TITLE
Add drawingWidth to API

### ISSUE THREAD

**Issue by hugolpz** [chanind/hanzi-writer#33]
You currently provide : 
* `drawingColor`: hex string, default '#555'. The color of the lines drawn by users during quizzes.

A good addition would be 
* `drawingWidth`: number, default '1' (px). The width of the lines drawn by users during quizzes.

![screenshot from 2018-01-26 18-52-41](https://user-images.githubusercontent.com/1420189/35453349-2767b19a-02ca-11e8-979d-8e0ef0daf565.png)

**Comment by chanind** [comment]
Do you mean the width of the stroke drawn by the user in quizzes? There is an option to control that currently, but it's undocumented. The option is called `drawingWidth` which is default 4. I'll add that to the documentation - there's no real reason to leave it undocumented.

There's also another undocumented option called `strokeWidth` which makes the strokes of each character thicker. Currently it's undocumented because if the number is set higher than around 15 or so the strokes will start getting clipped. That's fixable too, but I wasn't sure if there was a use-case for making the strokes of the character thicker so I left it undocumented for now. Is that a feature you want?

**Comment by hugolpz** [comment]
I was referring to the **drawing pen's mark**.

Our misunderstanding proves that `drawingWidth` would be more correct.

Same for other issue, `drawingPrecision` could be more correct.

**Comment by hugolpz** [comment]
Related to / Dependent on #25.

**Comment by chanind** [comment]
👍 makes sense, closing this issue
