### ISSUE TITLE
Add drawingPrecision to API

### ISSUE THREAD

**Issue by hugolpz** [chanind/hanzi-writer#34]
The current setting is too easy, drawing outside the stroke is still too easy to be correct. 

Could be good idea to add a variable for precision.

* `drawingPrecision` : number, default 1. The ratio of width of the "shadow stroke" to draw in in order to be correct, 0.5 is "all pen's stroke should be within the character's strokes".

Something like that.

![screenshot from 2018-01-26 18-52-41](https://user-images.githubusercontent.com/1420189/35453543-e3521ae4-02ca-11e8-9e3e-adf4d157c0e7.png)

**Comment by chanind** [comment]
This is a great idea! The reason it's so lenient currently is that when the outline is hidden users often draw strokes that can be pretty far off from the real position without realizing it. But, if it's an option that can be controlled then when Hanzi writer is used in an application the application author can control how accurate strokes need to be based on their judgement. I'll do some experimentation with this idea and set up a pull request implementing this idea.

**Comment by hugolpz** [comment]
Renamed. You understood the point. The naming can vary. It would define the unseen area to be in in order to have a correct drawing.

**Comment by hugolpz** [comment]
I made more test and it's really too easy currently. For 王 within 国, student can draw 3 horizontal lines in the middle and it ill be acceptef for the 3 horizontal lines of 王.

**Comment by chanind** [comment]
Yeah, this is definitely an issue. I'll work on improving matching this weekend.  It might even make sense to automatically be more strict with matching depending on the stroke number, or depending on if the outline is visible too. For example if there's no outline visible, it makes sense to be lenient on the position of the first stroke since users don't necessarily know exactly where it should be drawn, but less lenient afterwards since they have a reference point. Of course, if the outline is shown already then the user shouldn't have any confusion about where to draw the stroke.

**Comment by hugolpz** [comment]
+1 for the distinct precisions for with example / without example.

Need a default, but also customable.
Example : 
- With the current French MOOC it's 100% new learners, so it makes sense to be BFF (big-fingers-friendly :D )
- For confirmed users, like me, I would appreciate the stroke + a light margin, about 1/3 of the stroke cross section.

Point is, depending on the public / cohort level, we would need different requirement.

**Comment by chanind** [comment]
added a `leniency` param in 0.9.0 which allows controlling how strict grading is.
