### ISSUE TITLE
Consider repository cmn-audio

### ISSUE THREAD

**Issue by hugolpz** [chanind/hanzi-writer#36]
- Open audio : https://github.com/hugolpz/audio-cmn

There are syllabs audios via 1707 numeral tones filenames under CC-by-sa.
Could add audio to stroke order display

EDIT: [HSK data is corrupted](https://github.com/hugolpz/audio-cmn/issues/5)

**Comment by chanind** [comment]
This is a great library, thanks for sharing! It looks like this should already be usable alongside Hanzi Writer if users load the audio for the character being drawn alongside the character drawn by Hanzi Writer. I'd rather not try to combine the data from audio-cmn into Hanzi Writer directly since this library is just focused on drawing characters, and Hanzi Writer only supports single characters at a time while the audio files are often for complete words. I think it's most powerful if users of Hanzi Writer and audio-cmn can decide how to combine the 2 libraries for their use-case.

**Comment by hugolpz** [comment]
Separation of concern yes.
I have to clean up that repository, as i just found some critical bug in hsk and my shell skills are much better than in 2014 when i created it.

**Comment by hugolpz** [comment]
Note: The audio repository's data has been fixed today.
