### ISSUE TITLE
Constructor does real work

### ISSUE THREAD

**Issue by vaab** [chanind/hanzi-writer#55]
The current constructor of HanziWriter is calling ``setCharacter()``. Which is too soon in my code, and don't let me really manage when ``setCharacter()`` gets called. This is a minor issue, but is a little annoying and goes against some (debatable) design principles : a constructor should not do any real work (only setting up inner variables).

I'm willing to make a PR on that, taking into account the fact that you need to keep backwards compatibility.

To elaborate why it is better to avoid any complex behavior in constructors, here are a few discussion about that:
    http://misko.hevery.com/code-reviewers-guide/flaw-constructor-does-real-work/
    https://softwareengineering.stackexchange.com/questions/224063
    https://softwareengineering.stackexchange.com/questions/159193
    https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c41-a-constructor-should-create-a-fully-initialized-object
    https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-factory

As a fix, I would suggest to make it optional (default would still be to call ``setCharacter()``, but this should be removed in next major release), and provide a factory that would create the widget and load a character ``HanziWriter.Create()`` to still offer the use case of setting up and loading a character in one go.

I'm totally aware that it's kind'a matter of taste here, and I will very happily and kindly understand any dismissal of this proposal.

**Comment by chanind** [comment]
I think you're right, it's not ideal that the `HanziWriter` constructor does all this setup work, especially now that there's better error handling so the user might be required to call `setCharacter` manually anyway. It's probably better to use a factory method like you said for `HanziWriter.create()` or something similar which does what the current constructor does. The constructor can just take options and/or the target element, or maybe just leave everything blank and allow the user to set those up in multiple calls afterwards. As a transition, we can have the constructor work with variable numbers of arguments, so if the second argument is a string we can assume it's the current behavior, and if not assume it's the new behavior.

**Comment by Mikurox** [comment]
@vaab @chanind 
Hi guys, I totally agree with you on the above, I was going to raise the following bug when I saw this one

- create a new HanziWriter() object to initialise it (it's still hidden so not used yet)
`this.writer = new HanziWriter(characterDiv, character, {
			width: imgWidth,
			height: imgHeight,
			padding: 5,
			showOutline: true,
			drawingWidth: 22, // thickness of the drawing
			delayBetweenStrokes: 400, // milliseconds
			showCharacter: false,
			highlightOnComplete: false
		});`
- then later call the setCharacter method in order to really set the character we want you want
`this.writer.setCharacter(character);`

It creates 2 <g> elements in the <svg> one, with a bad overriding etc. as a consequence.

It may not have been the "way to use it" but in my case I would like to initialise everything before hand before even knowing which character I want to use.

So I'm looking forward for a fix as described above, or at least a fix on the new + set -> error

**Comment by chanind** [comment]
That's a good push to fix this. I'll work on a pr in the next few days!
