### ISSUE TITLE
Stroke accuracy too unforgiving?

### ISSUE THREAD

**Issue by tomcumming** [chanind/hanzi-writer#7]
From what i remember of skitter, it allowed you to miss the origin of the stroke by a much larger amount as long as you got the direction correct.

It looks like https://github.com/chanind/hanzi-writer/blob/master/src/StrokeMatcher.js#L11 is just measuring the distance from the absolutely positioned points?

**Comment by chanind** [comment]
It's using the average distance of the line the user draws to the line that passes between the 2 absolutely positioned points rather than just the 2 absolutely positioned points themselves. It also checks to make sure the length of the stroke the user drew is reasonable, that the stroke direction is correct, and that the start and end points of the stroke the user drew are reasonably close to the start and end points of the actual stroke. The consts at the top of the StrokeMatcher determine how lenient the matching is with regard to all those metrics. It's certainly possible it's too strict currently - if you want to mess around with the leniency constants at the top and make a PR I'm happy to change them.

**Comment by chanind** [comment]
Closing for now as there have since been a few changes to how the stroke matching works. Feel free to reopen if this is still an issue.
