### ISSUE TITLE
Last correct drawing of difficult stroke trigger onMistake event ?

### ISSUE THREAD

**Issue by hugolpz** [chanind/hanzi-writer#71]
I'am presently monitoring a lightly suspicious or inconsistent behavior.

Given a learner bumping on the difficult strokeNum X...
If drawing strokeNum X has 1 or more errors, then strokeNum X **final and correct drawing** fires the **`onMistake`** event, while the returned datapoints are actually defining **a correct line-drawing**. 

See the line with one cell bordered in blue: the drawingPath is correct but it fires a `onMistake` and set `var status="ongoing-mistake"`.

There is no way to mark this drawing as correct ?

![screenshot from 2018-03-01 11-47-38](https://user-images.githubusercontent.com/1420189/36841722-884f6b76-1d49-11e8-9bcc-05df6eb72863.png)

Note: in my code
- event `onMistake` event returns `var status=ongoing-mistake`
- event `onCorrectStroke`  event returns `var status=ongoing`
- event `onComplete` event returns `var status=complete`

EDIT: maybe need to have 
- `onMistakeDraw`
- `onCorrectDraw`
- `onMistake` :arrow_right: `onMistakeStroke`
- `onCorrectStroke`
- `onComplete` :arrow_right: `onCompleteCharacter`

**Comment by chanind** [comment]
I'm having trouble reproducing this. I've tried drawing strokes correctly and incorrectly on the character 玉 but I can't seem to get the incorrect callback to trigger. It looks like you're seeing the `onMistakeStroke` callback trigger on correct strokes, and the quiz otherwise behaves as if the stroke was drawn correctly? What specific steps need to occur to cause this to happen? How are your callbacks set up?

**Comment by hugolpz** [comment]
Received, I'am digging back in.

**Comment by hugolpz** [comment]
You are correct.
I'am testing your lib with my additional layer of code and no TDD.
I had a chain of ternaries which discretely injected that error into the spreadsheet. My apologizes.
