### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by ghost** [chanind/hanzi-writer#8]

**Comment by chanind** [comment]
The issue with small stokes seems valid to me. It seems reasonable to ignore the direction for those really tiny strokes.

The issue with serifs is a problem with the ZDT dataset IMO. It has some characters having serifs and other using a more hand-written font which is annoying. If you know of another higher-quality open-source dataset of characters and strokes, please let me know :). HanziWriter can't tell which type of character it's drawing so it just uses the points it sees to judge. I'll have to think more about how to handle that. Maybe just make stroke matching more lenient overall?

**Comment by ehallstr** [comment]
I see, I will think a little bit about it. Perhaps it is possible to smooth out the data. Got any tips how to get started with the source? It's ecmascript 6, right?

**Comment by chanind** [comment]
Yeah, it's es6. The default action for grunt is to build the JS and put it in the `dist` folder, so you should be able to `npm install` and then `grunt` to get the JS built. There's an `index.html` file in the `demo` folder that you can point your browser at to test in the browser. I haven't set up sourcemaps, but feel free to if you're up for it! So far I haven't had much trouble looking at the compiled JS and figuring out where it corresponds to in the source. `StrokeMatcher.getMatchingStroke()` is where all the matching logic is so that's probably the best place to start to improve matching.
