### ISSUE TITLE
Center Animation

### ISSUE THREAD

**Issue by ThoreBor** [chanind/hanzi-writer#81]
This is probably a stupid question, but how can I display the animation at the center of the screen?
I tried things like:
```html
<center>
	//Animate
</center>
```
The only way I found to change the horizontal location was to changed the width and not the height.
```javascript
var writer = new HanziWriter('character-target-div', '我', {
    width: 700,
    height: 150,
```

**Comment by chanind** [comment]
The easiest way is to center the div that you're drawing to into the center of the screen using CSS. There's a lot of ways to center in CSS depending on what your goal is (ex see [here](https://css-tricks.com/centering-css-complete-guide/)). For example, here's some code to center the div horizontally:
```
<div style="text-align: center">
  <div style="margin: 0 auto; width: 150px; height: 150px" id="character-target-div"></div>
</div>
```
Then, in JS:
```
var writer = new HanziWriter('character-target-div', '我', {width: 150, height: 150});
```
In reality it would be better to use a stylesheet rather than inline styles, but that basically do it I think. 

Does that work?

**Comment by ThoreBor** [comment]
Thank you! It works perfectly.
