### ISSUE TITLE
Question: Change stroke color of existing HanziWriter

### ISSUE THREAD

**Issue by nahanil** [chanind/hanzi-writer#87]
Is there any way to change the color of a HanziWriter that already exists in the DOM without messing with its internal variables?

Looks like I could make it work by hacking on `hw._canvas.svg` / `hw._renderState.state.character.main.strokeColor`, but that doesn't seem like a great idea 😈

Alternatively, looks like I might be able to use CSS to colour the paths instead of relying on a JS way..
```css
svg g g:nth-child(2) path {
  stroke: hotpink;
}
```
Not sure if there's a better way :)

**Comment by chanind** [comment]
There's currently not a method to do this, but it should be relatively easy to add. Just need to add a mutation in `characterActions.js` which changes some of the color variables and then add a method to `HanziWriter.js` to initiate it. I'll see if I can get a PR together implementing this.

**Comment by texh** [comment]
After taking a look at the options and given my use case I'm thinking that colouring the characters with CSS would actually be for the best - assuming it works in enough browsers (probably 'sorry IE users' kinda moment).

Basically, I'm trying to have characters coloured according to tone, with users able to select their choice of tone colours from a set list of common colouring schemes/define their own and have them updated without a page refresh as part of a Vue-based 'single-page' app deely - similar to the [Hanping dictionary](https://hanpingchinese.com/).
Turns out using CSS I can just swap out class names on the `<body />` or some other wrapper, ie `tone-coloring-<scheme>` and it'll take care of things across the board - plain text & the SVGs from HanziWriter...

For anyone else who finds this, I think I've settled on something like the following using, the tone colors mentioned by [Albert Wolfe](http://laowaichinese.net/tone-colors-and-what-pleco-did-with-them.htm).
```css
.tone-colors.tone-colors-dummit.color-char .char.t1 svg g g:nth-child(2) path {
  stroke: #f41d2f;
}
```

**Comment by chanind** [comment]
Using CSS like you described should work. I also went ahead and adding a PR to do this via a method on the `HanziWriter` instance in #88, since this seems like a reasonable feature to expect should exist. It turned out to be slightly trickier than I thought originally since tweening colors requires parsing color strings and turning them into corresponding color values, but it wasn't too bad. I'll get this merged soon.

**Comment by chanind** [comment]
`writer.updateColor(colorName, colorVal)` is now live in v1.1.0
