### ISSUE TITLE
Acute angle stroke in characters like 去 and 么 is too strict; curved stroke in 都 is too lenient.

### ISSUE THREAD

**Issue by peterolson** [chanind/hanzi-writer#94]
There is a particular stroke that my users have complained about being too difficult to write. It is the acute angle found in characters like 么 去 公 能 台 and so on.

Here is a screenshot of a rejected stroke from the [demo page](https://chanind.github.io/hanzi-writer/demo.html):

![strictangle](https://user-images.githubusercontent.com/920512/49417011-b962e080-f741-11e8-8cd7-a4581ecdc2ce.png)

The line is almost entirely inside the outline, so it seems excessively picky to reject it while some other strokes are very lenient, such as the right component of 都. Here is a screenshot of a stroke that was not rejected:

![lenientstroke](https://user-images.githubusercontent.com/920512/49417235-9553cf00-f742-11e8-9914-4e8e767cbf37.png)

**Comment by chanind** [comment]
It probably has something to do with the way the matcher does shape detection - need to do some more testing. Thanks for bringing this up!

**Comment by chanind** [comment]
It looks like this is due to the way curve normalization works in shape detection. Currently it only looks at the start and end points of the curve and then rescales the curve based on that. In the first example, since the end point is slightly off, when it rescales the long part of the acute angle gets pushed out really far and then the shape match fails. I think this should be fixable by using smarter curve normalization. Will work on a PR.

**Comment by chanind** [comment]
The matching improvements are live in v1.2.1. Let me know if this solves the issue!

**Comment by peterolson** [comment]
Thanks! As far as I can tell it seems to be working, but I'll let you know if I see any more issues.

It doesn't seem to be updated on the [demo page](https://chanind.github.io/hanzi-writer/demo.html). It seemed to be working reasonably well in my app after I did `npm update hanzi-writer` though.

**Comment by chanind** [comment]
Ah yeah it might take up to 24 hours to update on the demo page since it's set to load `1.2.x` from jsdelivr, and jsdelivr sometimes takes a bit for its cache to expire.
